### ISSUE TITLE
Compile error after importing due to unused "Newtonsoft" using

### ISSUE THREAD

**Issue by provencher** [handzlikchris/Unity.QuestRemoteHandTracking#1]
Upon Importing, I get compile errors in "HandsDataReceiver" and "HandsDataSender".

Both have an unused "using Newtonsoft.Json;". Removing them both solves the issue.

![image](https://user-images.githubusercontent.com/7420990/71730002-16323e00-2e0f-11ea-8b6f-b32ad599b17a.png)

**Comment by handzlikchris** [comment]
Thanks, removed in master
