### ISSUE TITLE
Can this be used with Virtual Desktop and SteamVR

### ISSUE THREAD

**Issue by guiglass** [handzlikchris/Unity.QuestRemoteHandTracking#10]
I would like to add finger tracking to an existing SteamVR Unity project.

I am afraid this is not possible and I wasted ~$500 on Facebook hardware.. But I was wondering if the project in this git would be capable of working along side SteamVR? 

Is it possible to use Virtual Desktop and SteamVR to run this game on a PC while seeing it in the Quest HMD and somehow retrieve the finger bend values?

I have been trying to find a solution for days and it's very difficult even trying to understand what is possible.

I would be very greatful if someone could help me find an answer, I have been losing a lot of sleep over trying to figure out how to access Oculus quest finger tracking data in my existing SteamVR game. I think it's impossible but some users say it has been done in other games.

How can I do this? I feel like I don't understand even the basic principals and have been at this for days!!

Thank you

**Comment by handzlikchris** [comment]
From my understanding (which could be wrong).

Virtual Desktop helps you run PC VR games in quest (it's streaming data from your pc to Quest and passing some of it back). So effectively your code is running in 'PC' world which doesn't have access to hand data.

To tap into it you need to be able to execute code natively in Quest. This tool does that but you need to run it as Quest Native (not via VD).

If you want to use Virtual Desktop in that setup then VD needs to pass that data as the code is running natively on Quest. Technically VD quest app can access hand data and pass it as well. Not sure how that'd work in practice as it's likely more complex stuff involved in proxying that data - your best bet would be to ask VD Developer.
