### ISSUE TITLE
Dependency on OculusSampleFramework in many classes

### ISSUE THREAD

**Issue by provencher** [handzlikchris/Unity.QuestRemoteHandTracking#2]
Dependency on "using OculusSampleFramework" causes errors if a project sets up an assembly structure where the only dependency is on the Oculus.VR dll.

It would be ideal to remove a dependency from Oculus' example code, and instead depend directly on the SDK.

**Comment by handzlikchris** [comment]
Thanks @provencher - this initial setup is build on top of OculusSampleFramework - so might not be easiest to reuse yet. I'll get rid of that as I move forward with other project.

**Comment by handzlikchris** [comment]
@provencher that's now also closed and merged into master, the setup is slightly different - you can find details in updated readme
