### ISSUE TITLE
Freezes on Quest : On launch or after few seconds when waering the headset.

### ISSUE THREAD

**Issue by satolas** [handzlikchris/Unity.QuestRemoteHandTracking#8]
Hello Chris,
I saw that the other similar issue was closed, and the Unity forum take ages to approve my post ^^

Little problem :
The headset freezes at load time.
But actually when I don't use it for a little while and I take it again the scene works for few seconds (with hand tracking on the Quest side) and then freeze again.
On the computer (Editor) nothing happens, and its hard to debug anyways since the quest is freezing.

Here is the quest log  :
**cd C:\Program Files\Unity\Hub\Editor\2019.2.6f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools
adb logcat -v brief**

Complete adb logcat (brief) in the text file : [Oculus Quest adb logcat brief.txt](https://github.com/handzlikchris/Unity.QuestRemoteHandTracking/files/4139148/Oculus.Quest.adb.logcat.brief.txt)
Here I paste a part, similar to yours :

```
I/VrApi  ( 5468): FPS=72,Prd=45ms,Tear=0,Early=72,Stale=0,VSnc=1,Lat=1,Fov=0,CPU4/GPU=2/2,1651/414MHz,OC=FF,TA=0/0/0,SP=N/N/N,Mem=1804MHz,Free=1678MB,PSM=0,PLS=0,Temp=27.0C/0.0C,TW=1.61ms,App=0.42ms,GD=0.00ms,CPU&GPU=1.70ms,LCnt=1,GPU%=0.15,CPU%=0.02(W0.05),DSF=1.00
E/Unity   ( 5468): SocketException: The requested address is not valid in this context
E/Unity   ( 5468):   at System.Net.Sockets.Socket.Bind (System.Net.EndPoint localEP) [0x00043] in <0e1afc3ce03d4e2ab478056348d6a9e9>:0
E/Unity   ( 5468):   at Assets.RemoteHandsTracking.HandsDataReceiver.Start () [0x00032] in <d2c4b3c0a45248e7a331cb3544dfe565>:0
E/Unity   ( 5468):
E/Unity   ( 5468): (Filename: <0e1afc3ce03d4e2ab478056348d6a9e9> Line: 0)
E/Unity   ( 5468):

```
What I don't get, is why is freezing, at least I could understand that the data could not be send through the Network so nothing happens in the Editor.
But that the Oculus Quest freezes, its like overreacting ^^

Hope this helps,
Don't hesitate to ask more info if  you need.

Cheers :)

**Comment by handzlikchris** [comment]
Hi Satolas,

Thanks, that helps.

I've recreated that and it'll be down to wrong IP in `HandsDataSender`. Or if you're certain that's correct IP then Quest can not reach, eg. due to FW / network setup.

I'll push a fix later this afternoon so it doesn't freeze when that happens - but that freeze is not cause of your issue.
