### ISSUE TITLE
Remote hand tracking in build

### ISSUE THREAD

**Issue by ibilab** [handzlikchris/Unity.QuestRemoteHandTracking#9]
Hi, as for now Oculus quest and link don't allow hand tracking. 

My question his: Could a remote hand tracking system similar to yours could be used to make hand tracking possible on a windows built app?

Thanks!

**Comment by handzlikchris** [comment]
I'm afraid not, once you're using link - you are kind of out of Quest - and hand data is not available. As far as I know you need to run Quest natively to get it.

There's a catch though as with Unity now supporting link (in editor / for development) - there must be a way they get that data from quest to editor / app.
